name: Automate Scripts

on:
  push:
    paths:
      - "data-workflow/ruwe-data/**.json"

jobs:
  automate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install TeXlive
        run: sudo apt-get update && sudo apt-get install texlive texlive-publishers texlive-science latexmk cm-super

      - name: Grant execute permission to script
        run: chmod +x data-workflow/data_transform.sh

      - name: Run data_transform.sh
        run: data-workflow/data_transform.sh

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy seaborn scipy matplotlib pandoc pypandoc pdflatex

      - name: Run airbnb_analysis.py
        run: python data-workflow/analysis/airbnb_analysis.py

      - name: Run generate_report.py
        run: python data-workflow/rapport/generate_rapport.py

      - name: Deploy PDF to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: data-workflow/rapport/
